{{- if .Values.fargateLog.enabled }}
# Specify namespace for Fargate logging.
kind: Namespace
apiVersion: v1
metadata:
  name: {{ .Values.fargateLog.namespace }}
  labels:
    aws-observability: {{ .Values.fargateLog.awsObservability }}
{{- end }}
